image: Visual Studio 2017

install:
  - cmd: git submodule update --init --recursive

before_build:
  - cmd: mkdir tmp
  - cmd: cd tmp
  - cmd: cmake -G "Visual Studio 15 Win64" ..

build:
  project: $(APPVEYOR_BUILD_FOLDER)\tmp\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - cmd: ctest -VV -C "Debug"
